                           ---BASIC PROBLESM--- 

-- Q1 List all unique  cities where Customers are located.

SELECT DISTINCT customer_city
FROM customers$;


--Q2-Count the number of orders placed in 2017.

SELECT COUNT(*) AS total_orders_2017
FROM orders$
WHERE YEAR(order_purchase_timestamp) = 2017;



ALTER TABLE dbo.order_items$
ALTER COLUMN price DECIMAL(18,2);


--Q3 Find the total sales per Categary

SELECT 
    p.[product category] AS category_name,
    SUM(oi.price) AS total_sales
FROM dbo.order_items$ oi
JOIN dbo.products$ p
    ON oi.product_id = p.product_id
GROUP BY p.[product category]
ORDER BY total_sales DESC;


--Q4 Calculate the percentage of orders that were paid in Installments

SELECT 
    (SUM(CASE WHEN payment_installments > 1 THEN 1 ELSE 0 END) * 100.0 
    / COUNT(*)) AS installment_percentage
FROM payments$;

--Q5. Count the number of customers from each state.

SELECT 
    customer_state,
    COUNT(customer_id) AS total_customers
FROM customers$
GROUP BY customer_state
ORDER BY total_customers DESC;

                            -- INTERMEDIATE PROBLEMS--


--Q1.Calculate number of orders per month in 2018.

SELECT 
    YEAR(order_purchase_timestamp) AS Year,
    MONTH(order_purchase_timestamp) AS Month,
    COUNT(order_id) AS Total_Orders

FROM orders$

WHERE order_purchase_timestamp >= '2018-01-01'
AND order_purchase_timestamp < '2019-01-01'

GROUP BY 
    YEAR(order_purchase_timestamp),
    MONTH(order_purchase_timestamp)

ORDER BY Year, Month;


--Q2 Find the average number of products per order,grouped by customer city.

SELECT 
    c.customer_city,
    AVG(Product_Count) AS Avg_Products_Per_Order
FROM
(
    SELECT 
        o.order_id,
        o.customer_id,
        COUNT(oi.product_id) AS Product_Count
    FROM orders$ o
    JOIN order_items$ oi
        ON o.order_id = oi.order_id
    GROUP BY 
        o.order_id,
        o.customer_id
) AS OrderProductCount
JOIN customers$ c
    ON OrderProductCount.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY Avg_Products_Per_Order DESC;

--Q3. Calculate the percentage of total revenue contributed by each product category.

SELECT 
    p.[product category],
    
    SUM(oi.price) AS Category_Revenue,

    SUM(oi.price) * 100.0 /
    (SELECT SUM(price) FROM order_items$) 
    AS Revenue_Percentage

FROM order_items$ oi

JOIN products$ p
    ON oi.product_id = p.product_id

GROUP BY p.[product category]

ORDER BY Revenue_Percentage DESC;

--Q4. Identify the correlation between product price and the number of times a product has been purchased.

SELECT 
    price,
    COUNT(product_id) AS Times_Purchased
FROM order_items$
GROUP BY price
ORDER BY price;

--Q5. Calculate the total revenue generated by each seller, and rank them by revenue.


SELECT 
    s.seller_id,

    SUM(oi.price) AS Total_Revenue,

    RANK() OVER 
    (ORDER BY SUM(oi.price) DESC) AS Seller_Rank

FROM order_items$ oi

JOIN sellers$ s
    ON oi.seller_id = s.seller_id

GROUP BY s.seller_id

ORDER BY Seller_Rank;


--ADVACED PROBLMES

--1.Calculate the moving average of order values for each customer over their order history

SELECT 
    o.customer_id,
    o.order_purchase_timestamp,
    SUM(p.payment_value) AS Order_Value,

    AVG(SUM(p.payment_value)) OVER
    (
        PARTITION BY o.customer_id
        ORDER BY o.order_purchase_timestamp
    ) AS Moving_Average

FROM dbo.orders$ o

JOIN dbo.payments$ p
ON o.order_id = p.order_id

GROUP BY 
    o.customer_id,
    o.order_purchase_timestamp

ORDER BY 
    o.customer_id,
    o.order_purchase_timestamp;

--Q2.Calculate the cumulative sales per month for each year

	SELECT 
    YEAR(o.order_purchase_timestamp) AS Year,
    MONTH(o.order_purchase_timestamp) AS Month,

    -- Monthly sales
    SUM(p.payment_value) AS Monthly_Sales,

    -- Cumulative sales
    SUM(SUM(p.payment_value)) OVER
    (
        PARTITION BY YEAR(o.order_purchase_timestamp)
        ORDER BY MONTH(o.order_purchase_timestamp)
    ) AS Cumulative_Sales

FROM dbo.orders$ o

JOIN dbo.payments$ p
ON o.order_id = p.order_id

GROUP BY 
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)

ORDER BY Year, Month;


--Q3.Calculate the year-over-year growth rate of total sales.

SELECT 
    YEAR(o.order_purchase_timestamp) AS Year,

    SUM(p.payment_value) AS Total_Sales,

    LAG(SUM(p.payment_value)) OVER
    (
        ORDER BY YEAR(o.order_purchase_timestamp)
    ) AS Previous_Year_Sales,

    (
        SUM(p.payment_value)
        - LAG(SUM(p.payment_value)) OVER
        (ORDER BY YEAR(o.order_purchase_timestamp))
    ) * 100.0

    /

    LAG(SUM(p.payment_value)) OVER
    (ORDER BY YEAR(o.order_purchase_timestamp))

    AS YoY_Growth_Percentage

FROM dbo.orders$ o

JOIN dbo.payments$ p
ON o.order_id = p.order_id

GROUP BY YEAR(o.order_purchase_timestamp)

ORDER BY Year;


--Q4.Calculate the retention rate of customers, defined as the percentage of customers who make another purchase within 6 months of their first purchase.

 WITH FirstPurchase AS
(
    SELECT
        customer_id,
        MIN(order_purchase_timestamp) AS first_purchase_date
    FROM dbo.orders$
    GROUP BY customer_id
),

NextPurchase AS
(
    SELECT
        fp.customer_id,
        fp.first_purchase_date,
        MIN(o.order_purchase_timestamp) AS next_purchase_date
    FROM FirstPurchase fp
    JOIN dbo.orders$ o
        ON fp.customer_id = o.customer_id
        AND o.order_purchase_timestamp > fp.first_purchase_date
    GROUP BY
        fp.customer_id,
        fp.first_purchase_date
)

SELECT

COUNT(customer_id) * 100.0 /

(
SELECT COUNT(*) FROM FirstPurchase
)

AS Retention_Rate_Percentage

FROM NextPurchase

WHERE DATEDIFF(MONTH, first_purchase_date, next_purchase_date) <= 6;



--Q5.Identify the top 3 customers who spent the most money in each year.


WITH CustomerYearSales AS
(
    SELECT 
        YEAR(o.order_purchase_timestamp) AS Year,
        o.customer_id,
        SUM(p.payment_value) AS TotalSpent

    FROM dbo.orders$ o

    JOIN dbo.payments$ p
        ON o.order_id = p.order_id

    GROUP BY 
        YEAR(o.order_purchase_timestamp),
        o.customer_id
),

RankedCustomers AS
(
    SELECT *,
    
    RANK() OVER
    (
        PARTITION BY Year
        ORDER BY TotalSpent DESC
    ) AS RankNum

    FROM CustomerYearSales
)

SELECT 
    Year,
    customer_id,
    TotalSpent,
    RankNum

FROM RankedCustomers

WHERE RankNum <= 3

ORDER BY Year, RankNum;

