## Business Requirement
**Calculate the total revenue generated by each seller,and rank them by revenue.**
SELECT 
    s.seller_id,

    SUM(oi.price) AS Total_Revenue,

    RANK() OVER 
    (ORDER BY SUM(oi.price) DESC) AS Seller_Rank

FROM order_items$ oi

JOIN sellers$ s
    ON oi.seller_id = s.seller_id

GROUP BY s.seller_id

ORDER BY Seller_Rank;
